#!/usr/bin/env bash
set -exuo pipefail

rm -rf dist; mkdir dist
cp -rp package README.md dist
for file in LICENSE CHANGELOG.md; do
  if [ -e "${file}" ]; then cp "${file}" dist; fi
done
node scripts/make-dist-package-json.cjs > dist/package.json

npm exec tsc-multi
npm exec tsc-alias -- -p tsconfig.build.json
node scripts/fix-index-exports.cjs
cp dist/index.d.ts dist/index.d.mts
cp tsconfig.dist-src.json dist/package/tsconfig.json

find dist -type f -exec node scripts/remove-triple-slash-references.cjs {} +
npm exec prettier -- --loglevel=warn --write .

# make sure that nothing crashes when we require the output CJS or
# import the output ESM
(cd dist && node -e 'require("@idealeap/gwt")')
(cd dist && node -e 'import("@idealeap/gwt")' --input-type=module)